dist: trusty
sudo: false
group: beta

language: node_js
node_js:
- node
addons:
  chrome: stable
  firefox: latest-esr
cache:
  directories:
  - node_modules
  - "$HOME/.cache/bower"
before_install:
- "if [ -d node_modules ] && [ x$(cat node_modules/.last-node-version 2>/dev/null) != x$(node -e 'console.log(process.version)') ]; then npm rebuild --update-binary && node -e 'console.log(process.version)' > node_modules/.last-node-version; fi"
script:
- LAUNCHPAD_BROWSERS=chrome xvfb-run npm test
deploy:
  provider: npm
  email: npm@collaborne.com
  api_key:
    secure: "GusxFIYL6EHUxvKSXTRuMRkIbecSKfQGVKTRu1issuIIEqyxPsR6rjFQpFlAzvQ5atL1qB9H6hbQcsNr2tfwnSgBudU765ElKqymnyU/q9WsVsKVdXOsJ0hndkrgy1pIrZpLNB9w+RlSM8A5ZeeY8OKmLS9iyVm7txaQQlbMafR0pSfSTvMVNmoNX5HAzw7ezBXhJAgxKco1Ubb/VXn+jO5rkLdnk36HbxjHo3MjsL98kwAmt32W3wjTAkv6LxXFCGz9LT0OLggpU6LzzRYlkDeS9qKB5dM5wD7+n+z7RIBqEM9WohLNzdNTVdnj9oU1nfr6sAhbO1IdJySQhFc9Y5kbDyrCKa6Sv4X/c8xPh1zC0XB9HoV3jPBzsnFVe5QrSaIA0XYYXAm7y1wK717K546KjNehLwtH95bi4ZXYx07dpFe9lfg6VsQ1TtuSPYv5x5lj1JPo1Huek2v5SMxnjezpsZNFK66xcewXNJYWsUFnuTir8/CQOFgbrkvgynmDsERieIh0O8/c7QG3Y8qTN34ISC+yJE1jnQMO1oP+R2UZ+nPdBSlNpnvyvu1SWvWZkqD97ZAxBiycTSP3RFVVZtwHsd4kVufOqhYyHJZw12sMRiXKvVEQ9rokbOPinFtUTt2+ERX7yOOw8sQzylZ5/NUnGlhUz2V7kIZt1zxwhwY="
  on:
    tags: true
    condition: $(node -e 'console.log("v" + require("./package.json").version)') = ${TRAVIS_TAG}
  skip_cleanup: true
