dist: trusty
sudo: false
group: beta
language: node_js
node_js:
- node
addons:
  firefox: 49.0.2
cache:
  directories:
  - node_modules
  - "$HOME/.cache/bower"
before_install:
- if [ -d node_modules ] && [ x$(cat node_modules/.last-node-version 2>/dev/null)!= x$(node -e 'console.log(process.version)') ]; then npm rebuild && node -e 'console.log(process.version)' > node_modules/.last-node-version; fi
script:
- xvfb-run npm test
after_success: '[ ${TRAVIS_PULL_REQUEST} = "false" ] && [ ${TRAVIS_BRANCH} = "master" ] && $(npm bin)/bower install -s https://${GH_TOKEN}@github.com/Collaborne/collaborne-build-tools.git && bower_components/collaborne-build-tools/gpages_build.sh Collaborne info@collaborne.com'
env:
  secure: BFMxh+KFCo+ED4FRRn65NNWSKFHBP9j9yCvs7uU1M5xvvTUW53aQ/ffE6uazDnTyQH5gOP0ibvUh08eJ1XRolJ/OAD2WtFFNpowM4E6jmZhpMfhm/M/+QWIiP+FIPdMtj7FKQgusEewbO+gqIGWmjvROKu9o48YXJaaL+7x34SHluEZ4PW5YIbjJNJqqBT6SvIas/S14+dEy0YhP1Amjh2lkvBQKFAAfjgkHvWhfXCRMtSQvfuOfd6CSflMu9vBjvRH/vQKPEDgMxFRyrED06oVe5Kyj1YjCOarzx5e1qBMG7fkwwE68UX/X2GNWeOGLExIOOhAtTnez8X5Kx9CtJwDG1MbKuNAL8tPe17J1RzUi+wlruqhunMyrTHwfjikHhawtdlJcCrOXKGrthJLAaX3KEgshcGGpkQfT/iC8+NIJj+mYzTLipbU1U/Iu88XjtGoRTgU+KR4glO/OxPrt1E3a82Vlq7z5vT7PF5C8hIUylejJLSMFDRQUbz35cUCAiRQcOG7irfykUU5yP6h65y8tnN3k5k7Kun2q271ehWeur88zy2eF8CYSImDT16OleaEbT4Bgjtc/uCV2pxmQQXE3dZJcgCePher3HMPyYt5beEcxjPJPG+jUyypuaBBRBo2n66vwtotn/TK+WrcxtfKMms3myoQzGXboDwrcJcA=
